#!/bin/zsh
set -euo pipefail

script_dir="${0:A:h}"
repo_root="${script_dir:h}"
config_dir="${repo_root}/esc-chatmail/Configuration"

required_vars=(
  GOOGLE_CLIENT_ID
  GOOGLE_API_KEY
  GOOGLE_PROJECT_NUMBER
  GOOGLE_PROJECT_ID
  GOOGLE_REDIRECT_URI
)

mkdir -p "${config_dir}"

missing_vars=()
for var_name in $required_vars; do
  if [[ -z "${(P)var_name:-}" ]]; then
    missing_vars+=("$var_name")
  fi
done

if (( ${#missing_vars[@]} == 0 )); then
  for configuration in Debug Release; do
    cat > "${config_dir}/${configuration}.xcconfig" <<EOF
// Generated by ci_scripts/ci_post_clone.sh for Xcode Cloud.
// Do not commit generated values.

GOOGLE_CLIENT_ID = ${GOOGLE_CLIENT_ID}
GOOGLE_API_KEY = ${GOOGLE_API_KEY}
GOOGLE_PROJECT_NUMBER = ${GOOGLE_PROJECT_NUMBER}
GOOGLE_PROJECT_ID = ${GOOGLE_PROJECT_ID}
GOOGLE_REDIRECT_URI = ${GOOGLE_REDIRECT_URI}
EOF
  done

  exit 0
fi

if [[ -s "${config_dir}/Debug.xcconfig" && -s "${config_dir}/Release.xcconfig" ]]; then
  print "Using repository xcconfig files because Xcode Cloud environment variables are not set."
  exit 0
fi

if (( ${#missing_vars[@]} > 0 )); then
  print -u2 "Missing required Xcode Cloud environment variables: ${missing_vars[*]}"
  print -u2 "Add them to your workflow or commit esc-chatmail/Configuration/Debug.xcconfig and Release.xcconfig."
  exit 1
fi
