#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="esc-chatmail/Configuration"

if [[ "${GITHUB_ACTIONS:-}" != "true" && "${ALLOW_LOCAL_CI_XCCONFIG_WRITE:-}" != "1" ]]; then
    echo "Scripts/write-ci-xcconfig.sh is intended for GitHub Actions." >&2
    echo "Set ALLOW_LOCAL_CI_XCCONFIG_WRITE=1 if you need to run it locally." >&2
    exit 1
fi

placeholder_contents() {
    cat <<'EOF'
// Generated by Scripts/write-ci-xcconfig.sh for CI.
GOOGLE_CLIENT_ID = ci-placeholder.apps.googleusercontent.com
GOOGLE_API_KEY = ci-placeholder-api-key
GOOGLE_PROJECT_NUMBER = 1234567890
GOOGLE_PROJECT_ID = ci-placeholder-project
GOOGLE_REDIRECT_URI = com.googleusercontent.apps.ci-placeholder
EOF
}

write_config() {
    local destination="$1"
    local contents="$2"

    if [[ -z "${contents}" ]]; then
        placeholder_contents > "${destination}"
        return
    fi

    printf '%s\n' "${contents}" > "${destination}"
}

mkdir -p "${CONFIG_DIR}"

shared_contents="${SHARED_XCCONFIG_CONTENTS:-}"
debug_contents="${DEBUG_XCCONFIG_CONTENTS:-$shared_contents}"
release_contents="${RELEASE_XCCONFIG_CONTENTS:-$shared_contents}"

write_config "${CONFIG_DIR}/Debug.xcconfig" "${debug_contents}"
write_config "${CONFIG_DIR}/Release.xcconfig" "${release_contents}"
