/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ChatsIndexRouteImport } from './routes/chats.index'
import { Route as ChatsConversationIdRouteImport } from './routes/chats.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatsRoute,
} as any)
const ChatsConversationIdRoute = ChatsConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => ChatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRouteWithChildren
  '/signin': typeof SigninRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/chats/': typeof ChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/chats': typeof ChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chats': typeof ChatsRouteWithChildren
  '/signin': typeof SigninRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/chats/': typeof ChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chats' | '/signin' | '/chats/$conversationId' | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/chats/$conversationId' | '/chats'
  id:
    | '__root__'
    | '/'
    | '/chats'
    | '/signin'
    | '/chats/$conversationId'
    | '/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRoute: typeof ChatsRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/chats/$conversationId': {
      id: '/chats/$conversationId'
      path: '/$conversationId'
      fullPath: '/chats/$conversationId'
      preLoaderRoute: typeof ChatsConversationIdRouteImport
      parentRoute: typeof ChatsRoute
    }
  }
}

interface ChatsRouteChildren {
  ChatsConversationIdRoute: typeof ChatsConversationIdRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsConversationIdRoute: ChatsConversationIdRoute,
  ChatsIndexRoute: ChatsIndexRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRoute: ChatsRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
